# This workflow will format all GDScript files in the repository using GDToolkit

name: GDScript Formatter

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install "gdtoolkit==4.*"
      
    - name: Format with GDToolkit
      run: |
        # Format all files in the repository
        gdformat .
    
    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'

        git add -A
        git commit -m "Format GDScript files with GDToolkit"
        git push
