# This workflow will update the submodule branch

name: Update Submodule Branch

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    
    - name: Setup Git
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git fetch
    
    - name: Clean Submodule
      run: |
        git checkout submodule
        git rm -r .

    - name: Update from Main
      run: |
        git checkout main -- addons/behaviour_toolkit
        mv addons/behaviour_toolkit/* .
        git rm -r addons/behaviour_toolkit

    - name: Commit to Submodule
      run: |
        git add -A
        git commit -am "Updated Submodule from Main"
        git push
